// NLS_CHARSET=UTF-8
define({
   submit: {label: "Kennwort ändern", a11y: "Kennwort ändern", tooltip: "Kennwort ändern"},
   cancel: {label: "Schließen", a11y: "Schließen", tooltip: "Schließen"},
   close: {label: "Schließen", a11y: "Schließen", tooltip: "Schließen"},
   title: {label: "Mein Kennwort Ändern"},
   caption: {label: "Kennwort von ${0} ändern"},
   oldpwd: {label: "* Aktuelles Kennwort:"},
   newpwd1: {label: "* Neues Kennwort:"},
   newpwd2: {label: "* Neues Kennwort:"},
   messages: {
	empty: "Bitte alle gekennzeichneten Felder ausfüllen.", 
	nomatch: "Die neuen Kennwörter unterscheiden sich.", 
	success: "Das Kennwort wurde erfolgreich geändert.",
	successdel: "Anwender wurde erfolgreich gelöscht.",
	unconfigured: "POST URL in config.js nicht definiert. Bitte wenden Sie sich an Ihren Administrator.",
	4: "Remote User nicht definiert. Bitte wenden Sie sich an Ihren Administrator.",
	10: "Verifikation des Personendokumentes ist fehlgeschlagen. Bitte wenden Sie sich an Ihren Administrator.",
	11: "Aktuelles Kennwort ist inkorrekt.",
	12: "Die neuen Kennwörter unterscheiden sich.",
	13: "Bitte alle gekennzeichneten Felder ausfüllen.",
	14: "Nicht alle erforderlichen Kennwörter gesendet. Bitte wenden Sie sich an Ihren Administrator.",
	15: "Der angegebene User wurde im Adressbuch nicht gefunden. Bitte wenden Sie sich an Ihren Administrator.",
	16: "Das neue Kennwort muss mindestens 8 Zeichen lang sein."
   },
   titleEUL: {label: "Externe Anwender Verwalten", width: "1100px"},
   nameCol: {label: "Name", width: "200px"},
   emailCol: {label: "E-Mail-Adresse", width: "230px"},
   companyCol: {label: "Firma", width: "230px"},
   actionCol: {label: "Aktion", width: "315px"},
   newUsrBtn: {label: "Neuer Anwender", a11y: "Neuer Anwender", tooltip: "Neuer Anwender"},
   resetPwdBtn: {label: "Passwort", a11y: "Passwort", tooltip: "Passwort"},
   editUsrBtn: {label: "Bearbeiten", a11y: "Bearbeiten", tooltip: "Bearbeiten"},
   delUsrBtn: {label: "Inaktivieren", a11y: "Inaktivieren", tooltip: "Inaktivieren"},
   helpBtn: {label: "Hilfe", a11y: "Hilfe", tooltip: "Hilfe"},
   deleteTitle: {label: "Anwender Inaktivieren"},
   deleteBtn: {label: "Inaktivieren", a11y: "Inaktivieren", tooltip: "Inaktivieren"},
   deleteMsg: {label: "Anwender <strong>${0}</strong> inaktiv setzen?"},
   helpTitle: {label: "Hilfe für die Verwaltung Externer Anwender", width: "600px" },
   helpMsg: "<h2>Berechtigungen</h2><p>Nur BeaS Angestellte d&#252;rfen externe Anwender verwalten.</p><br><h2>Liste der Externen Anwender</h2><p>Die Liste zeigt alle externe Anwender die im Domino Adressbuch angelegt wurden. Sie reflektiert nicht alle externen Anwenderprofile auf Harambee die bereits synchronisiert worden sind. Um nach einem bestimmten Anwender zu suchen, lassen Sie sich alle Anwender anzeigen und nutzen dann die Browser Suche (Strg+F) um den gewünschten Anwender zu finden.</p><br><h2>Neuen Anwender Anlegen</h2><p>Dr&#252;cken Sie die Schaltfl&#228;che um einen neuen Anwender anzulegen. Bitte f&#252;llen Sie alle Felder aus. Falls die Kombination des angegebenen Vor- und Nachnamen oder die angegebene E-Mail-Adresse bereits vergeben ist, erhalten Sie eine Fehlermeldung. Wenn alles passt, erhalten Sie eine Best&#228;tigungsnachricht und das Passwort des neuen externen Anwenders wird angezeigt. Bitte notieren Sie sich das Passwort um es dem neuen Anwender mitteilen zu k&#246;nnen. In einer zuk&#252;nftigen Version werden Sie zus&#228;tzlich die Option erhalten, eine E-Mail-Benachrichtigung mit dem Passwort direkt an den Anwender zu senden. Der Anwender wird sich sp&#228;testens nach 1,5 Stunden auf Harambee anmelden k&#246;nnen da das Personendokument zun&#228;chst nach Harambee synchronisiert werden muss.</p><br><h2>Passwort Zur&#252;cksetzen</h2><p>Dr&#252;cken Sie die Schaltfl&#228;che um das Passwort des Anwenders zur&#252;ckzusetzen. Das neue Passwort für den externen Anwender wird angezeigt. Bitte notieren Sie sich das neue Passwort um es dem Anwender mitteilen zu k&#246;nnen. In einer zuk&#252;nftigen Version werden Sie zus&#228;tzlich die Option erhalten, eine E-Mail-Benachrichtigung mit dem Passwort direkt an den Anwender zu senden.</p><br><h2>Externen Anwender Bearbeiten</h2><p>Dr&#252;cken Sie die Schaltfl&#228;che um die im Domino Adressbuch hinterlegten Anwenderdetails zu bearbeiten, d.h. Vor- und Nachname, E-Mail-Adresse und Firmenname des Anwenders.</p><br><h2>Externen Anwender Inaktivieren</h2><p>Dr&#252;cken Sie die Schaltfl&#228;che um die Inaktivierung des externen Anwenderprofils zu beantragen. Das Domino Personendokument wird nicht gel&#246;scht, sondern dessen Typ auf archiviert gesetzt. Damit k&#246;nnen Administratoren den Anwender bei Bedarf reaktivieren. Sp&#228;testens nach 1,5 Stunden wird das Harambee Profil auf inaktiv gesetzt.</p>",
   resetTitle: {label: "Passwort Zurücksetzen"},
   resetSubmit: {label: "Passwort zurücksetzen", a11y: "Passwort zurücksetzen", tooltip: "Passwort zurücksetzen"},
   resetOption1: {label: "Passwort dem Anwender via E-Mail senden"},
   resetOption2: {label: "Passwort nur auf dem Bildschirm anzeigen"},
   resetInfoMsg: "Das Kennwort für <strong>${0}</strong> zurücksetzen.",
   resetNewPwdMsg: "Neues Kennwort:"
});

